// This file has been auto-generated by the rundll.NET versioner

using System.Reflection;
using RunDLL;

[assembly: AssemblyVersion("1.1.0.426")]
[assembly: AssemblyFileVersion("1.1.0.426")]
[assembly: BuildInformation(
    Date = "2016-06-05, 17:39:19:324649",
    Machine = "E56B09220E2B64EBC2B0631D5BE5840FA51C7CB89E811E69903345EEE3FB3D8C",
    CSHash = "FEB15D500935F04F894B364360900919E555E68B049AA094ABFA97E0596C5D44",
    User = "09F85755517734972287D65F5CB172220B274FB54A5DAB8AB1AFF06BA8FB49D8"
)]